Payments functionality
samigeorgiev/SpecialistsServicesCatalog pull request #10
Opened 2021-02-08 18:56 UTC by samigeorgiev

2021-02-13 12:17 UTC, VladimirNachev requested changes

2021-02-13 12:17 UTC, VladimirNachev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/dtos/MakeStripePaymentRequest.java
> +public class MakeStripePaymentRequest {
Why the name of the class is not a noun ?

2021-02-13 12:17 UTC, VladimirNachev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/entities/Specialist.java
>          return user;
If you can mutate the 'user' object, then you are breaking the encapsulation of the 'Specialist' class.

2021-02-13 12:17 UTC, VladimirNachev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/jobs/PaymentsJobs.java
> +        System.out.println("Specialists payouts");
Should we print to the standard output here ? (or we should instead use a logger)

2021-02-13 12:17 UTC, VladimirNachev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/services/PaymentsService.java
> +        if (serviceRequest.isPaid() || serviceRequest.getStatus() != ServiceRequestStatus.FINISHED) {
I would rather extract that logic here in a separate helper method 'isServiceRequestPayable' and use it's negation in the check here.

2021-02-13 12:17 UTC, VladimirNachev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/services/PaymentsService.java
> +        Charge charge;
We can extract the payment in a separate helper method (lines 34-48) (it could be named 'pay(requestedServicePrice, requestTokenId)')

2021-02-13 12:17 UTC, VladimirNachev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/services/SpecialistsService.java
>          specialistRepository.save(specialist);
Why controllers, services etc. are named in plural ('UsersController', 'SpecialistsController', 'SpecialistsService') but their repositories are named in single ?

2021-02-13 12:17 UTC, VladimirNachev commented on frontend/src/App.tsx
> +            {/*<StripeCheckout*/}
Should not we remove that commented code ?

2021-02-13 12:17 UTC, VladimirNachev commented on frontend/src/hooks/UserActions/BecomeSpecialist/useBecomeSpecialist.ts
> +                returnUrl: 'http://localhost:3000',
These hardcoded urls should be at least made constants in 'constants.ts' file for example.

2021-02-13 12:17 UTC, VladimirNachev commented on frontend/src/hooks/UserActions/BecomeSpecialist/useBecomeSpecialist.ts
> +}
No new line at the end of file. (Have you run linter ?)

2021-02-15 21:26 UTC, samigeorgiev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/entities/Specialist.java
>          return user;
try to make getters and setters less visible

2021-02-16 06:59 UTC, merged

2021-02-16 09:39 UTC, samigeorgiev commented on backend/src/main/java/com/sscatalog/specialistsservicescatalog/entities/Specialist.java
>          return user;
it is possible to omit unused getters and setters